### ISSUE TITLE
Update course survey link

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/rnaseq-workshop-2023#4]
Once provided by MB, add this to materials homepage https://sydney-informatics-hub.github.io/rnaseq-workshop-2023/#course-survey

**Comment by georgiesamaha** [comment]
@nandan75 link to survey is: https://www.surveymonkey.com/r/rnaseq2023

**Comment by nandan75** [comment]
ok I will add this to  https://sydney-informatics-hub.github.io/rnaseq-workshop-2023/#course-survey

**Comment by nandan75** [comment]
Added
